apiVersion: apps/v1
kind: Deployment
metadata:
  name: jogoteca
  namespace: gameproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jogoteca
  template:
    metadata:
      labels:
        app: jogoteca
    spec:
      containers:
        - name: jogoteca
          image: kisten/gameproject:v8
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: mysql.gameproject.svc.cluster.local
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password

